### ISSUE TITLE
Support JALR (Stretch goal) (Core)

### ISSUE THREAD

**Issue by kevinacahalan** [SWIM-ucf/SWIM#111]

**Comment by kevinacahalan** [comment]
Has this instruction been implemented in the parser?

**Comment by jerrettl** [comment]
> Has this instruction been implemented in the parser?

Currently not implemented. @ehraiford correct me if I am wrong

**Comment by kevinacahalan** [comment]
#211 is effectively the same issue, JALR and JR are the same instruction for MIPS release 6
