### ISSUE TITLE
Initialized SP to 65535

### ISSUE THREAD

**Issue by kevinacahalan** [SWIM-ucf/SWIM#256]
Current there is a bug where SP it initialized to MEMSIZE, should be (MEMSIZE -1)

**Comment by jerrettl** [comment]
No, initializing to MEMSIZE is intended.

**Comment by jerrettl** [comment]
The assembly programmer is expected to move $sp in the event of adding data to the stack. By initializing it to MEMSIZE - 1, you will effectively always have one unused byte of memory at the end.
